--[[
	Bagnon Config Localization Information: English Language
		This file must be present to have partial translations
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'enUS', true)

L.Columns = 'Columns'
L.Scale = 'Scale'
L.Spacing = 'Spacing'
L.Opacity = 'Opacity'
L.FrameColor = 'Frame Color'
L.FrameBorderColor = 'Frame Border Color'
L.Frame = 'Frame'
L.Inventory = 'Inventory'
L.Bank = 'Bank'
L.KeyRing = 'Keyring'
L.GuildBank = 'Guild Bank'
L.LockFramePositions = 'Lock frame positions'
L.ShowEmptyItemSlotBackground = 'Display a background for empty item slots'
L.HighlightItemsByQuality = 'Highlight items by quality'
L.HighlightQuestItems = 'Highlight quest items'
L.ReverseSlotOrdering = 'Reverse bag slot ordering'
L.ColorItemSlotsByBagType = 'Color empty item slots by bag type'
L.FrameLayer = 'Layer'
L.EnableBagFrame = 'Enable bag frame'
L.EnableMoneyFrame = 'Enable money frame'
L.EnableDBOFrame = 'Enable databroker frame'
L.EnableSearchToggle = 'Enable search toggle'
L.EnableOptionsToggle = 'Enable options toggle'
L.EnableSortButton = 'Enable sort button'
L.EnableSlotCounter = 'Show free slot counter'
L.EnableFrame_inventory = 'Enable inventory frame'
L.EnableFrame_bank = 'Enable bank frame'
L.EnableFrame_keys = 'Enable keyring'
L.SettingRequiresRestart = 'This setting will take effect after the interface is reloaded.'
L.EnableAutoDisplay_bank = 'Display inventory when visiting the bank'
L.EnableAutoDisplay_ah = 'Display inventory when visiting the auction house'
L.EnableAutoDisplay_vendor = 'Display inventory when visiting a vendor'
L.EnableAutoDisplay_trade = 'Display inventory when trading items'
L.EnableAutoDisplay_craft = 'Display inventory when crafting'
L.EnableAutoDisplay_mail = 'Display inventory when checking a mailbox'
L.EnableAutoDisplay_guildbank = 'Display inventory when visiting the guild bank'
L.EnableAutoDisplay_player = 'Display inventory when opening the player frame'
L.DisplaySettings = 'Automatic Display'
L.DisplaySettingsTitle = 'Automatic frame display settings'
L.FrameSettings = 'Frame Settings'
L.FrameSettingsTitle = 'Configuration settings specific to a Bagnon frame'
L.GeneralSettings = 'General Settings'
L.GeneralSettingsTitle = 'General configuration settings for Bagnon'
L.EnableBlizzardBagPassThrough = 'Display Blizzard frames for disabled bags'
L.EnableBagBreak = 'Enable bag break layout'
L.ColorSettings = 'Color Settings'
L.ColorSettingsTitle = 'Item slot coloring settings'
L.ItemHighlightOpacity = 'Item highlight brightness'
L.ItemSlotColor_ammo = 'Ammo bag slot color'
L.ItemSlotColor_trade = 'Trade bag slot color'
L.ItemSlotColor_shard = 'Soul bag slot color'
L.ItemSlotColor_keyring = 'Keyring slot color'

--sections
L.SectionWindows = 'Windows'
L.SectionBehavior = 'Behavior'
L.SectionItemSlots = 'Item Slots'
L.SectionMaintenance = 'Maintenance'
L.SectionComponents = 'Components'
L.SectionLayout = 'Layout'
L.SectionAppearance = 'Appearance'
L.SectionHighlighting = 'Item Highlighting'
L.SectionSlotColors = 'Empty Slot Colors'
L.SectionAutoDisplay = 'Open the inventory automatically'

--highlight style
L.ItemBorderStyle = 'Highlight style'
L.BorderStyle_thin = 'Thin border'
L.BorderStyle_glow = 'Classic glow'

--buttons & dialogs
L.ResetPosition = 'Reset Position'
L.ResetFrame = 'Reset Frame'
L.ResetFramePositions = 'Reset All Positions'
L.ResetAllSettings = 'Reset All Settings'
L.ConfirmResetFrame = 'Reset every setting for the %s frame back to its default?'
L.ConfirmResetAll = 'Reset ALL Bagnon settings? Your interface will reload.'
L.ReloadUI = 'Reload UI'
L.Later = 'Later'
L.SlashHint = 'Type /bagnon in chat for a list of commands.  Version %s'

--tooltips
L.Tip_EnableFrame_inventory = 'Use Bagnon\'s single window instead of the default bags.'
L.Tip_EnableFrame_bank = 'Use Bagnon\'s single window instead of the default bank.'
L.Tip_EnableFrame_keys = 'Use Bagnon\'s window for the keyring.'
L.Tip_EnableBlizzardBagPassThrough = 'When a bag is hidden in Bagnon, opening it shows the standard Blizzard bag instead.'
L.Tip_LockFramePositions = 'Prevents moving frames by dragging their title. Hold Alt to move a locked frame.'
L.Tip_ShowEmptyItemSlotBackground = 'Draws the classic slot background in empty item slots.'
L.Tip_ResetFramePositions = 'Moves every Bagnon frame back to its default position. Useful if a frame ended up off screen.'
L.Tip_ResetAllSettings = 'Restores every Bagnon setting to its default and reloads the interface.'
L.Tip_EnableBagFrame = 'Adds a bag bar (toggled with the backpack button) for showing, hiding and swapping bags.'
L.Tip_EnableMoneyFrame = 'Shows your gold in the footer. Hover it for realm totals when Bagnon_Forever is enabled.'
L.Tip_EnableDBOFrame = 'Shows a DataBroker plugin in the footer. Scroll over it to switch plugins.'
L.Tip_EnableSearchToggle = 'Adds a search button to the header. Double-clicking the title also opens search.'
L.Tip_EnableOptionsToggle = 'Adds a button to the header that opens these settings.'
L.Tip_EnableSortButton = 'Adds a button that sorts, stacks and compresses items using BankStack.'
L.Tip_EnableSlotCounter = 'Shows free and total bag slots in the footer. Turns orange when almost full and red when full.'
L.Tip_ReverseSlotOrdering = 'Lists bags from last to first.'
L.Tip_EnableBagBreak = 'Starts each bag on its own row.'
L.Tip_Columns = 'How many item slots are shown per row.'
L.Tip_Spacing = 'Space between item slots, in pixels.'
L.Tip_Scale = 'Size of this frame. The frame keeps its screen position when scaled.'
L.Tip_Opacity = 'Transparency of the whole frame, including items.'
L.Tip_FrameLayer = 'Which windows this frame draws above or below.'
L.Tip_FrameColor = 'Background color and transparency.'
L.Tip_FrameBorderColor = 'Border color. Each frame uses a different color by default so they are easy to tell apart.'
L.Tip_ResetPosition = 'Moves this frame back to its default position.'
L.Tip_ResetFrame = 'Restores every setting on this page to its default.'
L.Tip_HighlightItemsByQuality = 'Colors the border of uncommon and better items by rarity.'
L.Tip_HighlightQuestItems = 'Outlines quest items in yellow.'
L.Tip_ItemBorderStyle = 'Thin border draws a crisp outline inside the slot. Classic glow uses the original action button glow.'
L.Tip_ItemHighlightOpacity = 'How strongly highlight borders are drawn.'
L.Tip_ColorItemSlotsByBagType = 'Tints empty slots in ammo, profession and soul bags, and the keyring, so you can tell special bags apart.'
L.Tip_AutoDisplay = 'Opens your inventory when this window opens, and closes it again afterwards.'
L.Warning_RequiresBankStack = 'Requires the BankStack addon.'
L.Warning_NotAvailableForFrame = 'Not available for this frame.'
